version: '3.0'

services:
  db:
    image: postgres:9.6-alpine
    container_name: main_db
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - ./.env

  redis:
    image: redis:4.0-alpine
    container_name: khatangatao_redis
    depends_on:
      - db

  backend_worker:
    image: khatangatao/khatangatao_backend:0.1
    container_name: khatangatao_backend_worker
    volumes:
      - "./data/media:/opt/media"
      - "../certs:/opt/certs:ro"
    env_file:
      - ./.env
    entrypoint: ./run_backends.sh worker

  backend:
    image: khatangatao/khatangatao_backend:0.1
    container_name: khatangatao_backend
    volumes:
      - "./data/media:/opt/media"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  nginx:
    image: khatangatao/khatangatao_nginx:0.1
    container_name: khatangatao_nginx
    volumes:
      - "./data/media:/opt/media:ro"
      - "./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 80:80
    depends_on:
      - backend