version: '3.0'

services:
  db:
    image: mdillon/postgis:9.6-alpine
    container_name: main_db
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - ./.env
    ports:
      - "5432:5432"