version: '3.0'

services:
  db:
    image: postgres:9.6-alpine
    container_name: main_db
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0-alpine
    container_name: khatangatao_redis
    depends_on:
      - db
    ports:
      - "6379:6379"

  backend_worker:
    image: khatangatao
    container_name: khatangatao_backend_worker
    volumes:
      - "./data/media:/opt/media"
      - "../certs:/opt/certs:ro"
    env_file:
      - ./.env
    entrypoint: ./run_backends.sh worker

  backend:
    image: khatangatao
    container_name: khatangatao_backend
    volumes:
      - "./data/media:/opt/media"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    ports:
      - 8001:8000

  nginx:
    image: khatngatao_nginx
    container_name: khatangatao_nginx
    volumes:
      - "./data/media:/opt/media:ro"
      - "./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 8000:80
    depends_on:
      - backend